### ISSUE TITLE
Flow Z13, Unhandled Exception

### ISSUE THREAD

**Issue by UnknownLOL** [seerge/g-helper#1303]
Clicking "Fans + Power" button throws an exception in the new version of G-Helper (0.1.22.0). Upgraded from 0.1.20.0 where it works fine.

Click the button.

**Expected behavior**
Fan and power curves window should open.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Flow Z13 GZ301ZE 
 - XGM 4090 (Doesn't matter whether it is connected or not)

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- Asus services running: 0

**Additional context**
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GHelper.Fan.FanSensorControl.GetFanMax(AsusFan device) in C:\Users\Serge\g-helper\app\Fan\FanSensorControl.cs:line 73
   at GHelper.Fans.ChartYLabel(Int32 percentage, AsusFan device, String unit) in C:\Users\Serge\g-helper\app\Fans.cs:line 593
   at GHelper.Fans.SetAxis(Chart chart, AsusFan device) in C:\Users\Serge\g-helper\app\Fans.cs:line 610
   at GHelper.Fans.SetChart(Chart chart, AsusFan device) in C:\Users\Serge\g-helper\app\Fans.cs:line 655
   at GHelper.Fans.InitFans() in C:\Users\Serge\g-helper\app\Fans.cs:line 890
   at GHelper.Fans.InitAll() in C:\Users\Serge\g-helper\app\Fans.cs:line 257
   at GHelper.Fans..ctor() in C:\Users\Serge\g-helper\app\Fans.cs:line 173
   at GHelper.SettingsForm.FansToggle(Int32 index) in C:\Users\Serge\g-helper\app\Settings.cs:line 623
   at GHelper.SettingsForm.ButtonFans_Click(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Settings.cs:line 641
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Log:
[log.txt](https://github.com/seerge/g-helper/files/12589108/log.txt)

**Comment by seerge** [comment]
@UnknownLOL thanks for spotting, can you check this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12589208/GHelper.zip)

**Comment by UnknownLOL** [comment]
> @UnknownLOL thanks for spotting, can you check this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/12589208/GHelper.zip)

Yes, this one works alright. Thanks for quick fix)
