### ISSUE TITLE
error everytime I switch performance modes with a shortcut.

### ISSUE THREAD

**Issue by jzhang802** [seerge/g-helper#143]
Getting this popup everytime I toggle performance with like FN+F5

No issue when switching from the g-helper window. Have armoury crate uninstalled.

System.IO.IOException: The process cannot access the file 'C:\Users\username\AppData\Roaming\GHelper\config.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at AppConfig.setConfig(String name, Int32 value)
   at GHelper.SettingsForm.SetPerformanceMode(Int32 PerformanceMode, Boolean notify)
   at GHelper.SettingsForm.CyclePerformanceMode()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by seerge** [comment]
Any chance you have 2 copies of the same app running in tray ?

**Comment by jzhang802** [comment]
oh that was the issue. I assumed it closed when i click the x. had to click 'quit'.
