### ISSUE TITLE
[Bug] Dark mode broken in 0.47

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#189]
**Describe the bug**
GHelper in dark mode now (v0.47) shows grey highlight in the text of checkboxes. I don't think this is intended, in version 0.46 it was ok.

**Clear scenario to Reproduce**
1. Set Windows to dark mode.
2. Use GHelper 0.47

**Expected behavior**
No grey highlight in the text of checkboxes (like v0.46).

**App Logs**
```
03/04/2023 21:57:00: ------------
03/04/2023 21:57:00: App launched
03/04/2023 21:57:00: AutoSetting for Online
03/04/2023 21:57:00: BatteryLimit = 80 : OK
03/04/2023 21:57:00: PerformanceMode = 0 : OK
03/04/2023 21:57:00: FanCPU = 14-1E-31-44-48-4D-51-62-01-01-05-1A-22-29-30-45 : OK
03/04/2023 21:57:00: FanGPU = 14-1E-32-44-48-4D-51-62-03-04-07-1F-26-2D-34-4A : OK
03/04/2023 21:57:00: Boost 0
03/04/2023 21:57:00: Eco flag : -65536
03/04/2023 21:57:00: Mux flag : -65536
03/04/2023 21:57:01: Screen = 120Hz : OK
03/04/2023 21:57:01: ScreenOverdrive = 0 : 0
03/04/2023 21:57:01: Monitor Power On
03/04/2023 21:57:05: Failed reading GPU temp
03/04/2023 21:57:05: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
03/04/2023 21:57:07: Failed reading GPU temp
03/04/2023 21:57:07: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
03/04/2023 21:57:09: Failed reading GPU temp
03/04/2023 21:57:09: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
03/04/2023 21:57:12: Failed reading GPU temp
03/04/2023 21:57:12: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
```

**Screenshots or screencasts**
![imagen](https://user-images.githubusercontent.com/62946623/229612847-db2a721a-4b12-4c3a-90e2-ef9b498c15e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: ROG Zephyrus G14 GA401IV

**Asus software**
- Asus System Control Interface V3

**Comment by seerge** [comment]
@marcelomijas for the Extra & Main window - i agree, that's a bug
But for Fans+Power I kind of did that intentionally, as I have removed buttons there (i may try to make borders a bit rounded here tho)

**Comment by seerge** [comment]
I have reuploaded fix over same version https://github.com/seerge/g-helper/releases/tag/v0.47
