### ISSUE TITLE
Occasional Crash on Startup

### ISSUE THREAD

**Issue by MikeMaximus** [seerge/g-helper#1992]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The application will sometimes crash when starting up on log-in.

2024-01-28 7:28:59 AM in the log is the most recent crash output.

### How to reproduce the bug?

This crash doesn't happen every time.

1.  Set G-Helper to "Run on Startup"
2.  Reboot.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14076215/log.txt)

### Device and Model

ASUS TUF Gaming A15 FA506IV

### Additional information.

This is the crash information from event viewer.

Faulting application name: GHelper.exe, version: 0.148.0.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x1cb8
Faulting application start time: 0x01da51edef2c4e60
Faulting application path: C:\Users\Public\Applications\GHelper\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: dbe4c102-3c78-449f-8acd-04d7f7c657e2
Faulting package full name: 
Faulting package-relative application ID: 

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.148

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@MikeMaximus hello,

Can you please check for and post here another crash info from event viewer. They usually come in pairs, where first one - is the one you posted (it doesn't actually contain anything specific) and second contains exact reasons of an exception.

Thanks :)

**Comment by MikeMaximus** [comment]
Sorry I missed that!  Here you go.

```Application: GHelper.exe
CoreCLR Version: 7.0.1423.51910
.NET Version: 7.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Windows.Forms.PropertyStore.SetObject(Int32 key, Object value)
   at GHelper.SettingsForm.VisualiseBatteryFull() in D:\a\g-helper\g-helper\app\Settings.cs:line 1401
   at GHelper.Battery.BatteryControl.UnSetBatteryLimitFull() in D:\a\g-helper\g-helper\app\Battery\BatteryControl.cs:line 22
   at HardwareControl.ReadSensors() in D:\a\g-helper\g-helper\app\HardwareControl.cs:line 215
   at GHelper.SettingsForm.RefreshSensors(Boolean force) in D:\a\g-helper\g-helper\app\Settings.cs:line 1070
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by seerge** [comment]
@MikeMaximus great! Thanks for spotting.

Reason was UI crashing on attempt on uncheck 100% charge button in UI after noticing that it's already charged :)

This build should fix it
[GHelper.zip](https://github.com/seerge/g-helper/files/14076492/GHelper.zip)

If it doesn't by some reason - let me know

**Comment by MikeMaximus** [comment]
Thanks! I'll test it out. 👍
