### ISSUE TITLE
TUF GAMING M3 (Gen II) Unhandled exception

### ISSUE THREAD

**Issue by lenverwazo** [seerge/g-helper#2454]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Pressing on the Peripheral button "TUF GAMING M3 (Gen II)" causes an unhandled exception: "Index was outside the bounds of the array."

### How to reproduce the bug?

Simply by pressing on the Peripheral button "TUF GAMING M3 (Gen II)"

### Logs

4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II) (GUI): Initialized capabilities. Synchronizing mouse data
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Write took 3ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Active Profile 1, Active DPI Profile: 0
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read DPI Setting 1: DPI: 800, Color (255, 0, 0)
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read DPI Setting 2: DPI: 1600, Color (255, 0, 0)
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read DPI Setting 3: DPI: 3200, Color (255, 0, 0)
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read DPI Setting 4: DPI: 6400, Color (255, 0, 0)
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Pollingrate: 1000 Hz (PR1000Hz)
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Angle Snapping enabled: False, Angle Adjustment: 0°
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read Debouce Setting: MS12
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II): Read RGB Setting for Zone Logo: LightingMode: Static, Color (255, 255, 255), Brightness: 100%, LightingSpeed: Medium, RandomColor:False, AnimationDirection:Clockwise
4/19/2024 12:39:37 PM: TUF GAMING M3 (Gen II) (GUI): Mouse data synchronized

### Device and Model

F15 FX507VI

### Additional information.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GHelper.AsusMouseSettings.VisualizeCurrentDPIProfile() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 869
   at GHelper.AsusMouseSettings.VisualizeMouseSettings() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 693
   at GHelper.AsusMouseSettings.RefreshMouseData() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 473
   at GHelper.AsusMouseSettings..ctor(AsusMouse mouse) in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 114
   at GHelper.SettingsForm.ButtonPeripheral_Click(Object sender, EventArgs e) in D:\a\g-helper\g-helper\app\Settings.cs:line 1810
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.165.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lenverwazo can you try this build, and post a full log from it ?

[GHelper.zip](https://github.com/seerge/g-helper/files/15043794/GHelper.zip)

**Comment by lenverwazo** [comment]
Hi! Here's the complete logs with this new version.
```
4/19/2024 8:50:55 PM: ------------
4/19/2024 8:50:55 PM: App launched: ASUS TUF Gaming F15 FX507VI_FX507VI :0.167.0.0en-US
4/19/2024 8:50:55 PM: Matrix control device was not found on your machine.
4/19/2024 8:50:55 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
4/19/2024 8:50:55 PM: NVIDIA GeForce RTX 4070 Laptop GPU
4/19/2024 8:50:56 PM: CPU: -1 - 13th Gen Intel(R) Core(TM) i7-13620H - Intel64 Family 6 Model 186 Stepping 2
4/19/2024 8:50:56 PM: AutoSetting for Online
4/19/2024 8:50:56 PM: Eco flag : 0
4/19/2024 8:50:56 PM: Mux flag : 0
4/19/2024 8:50:56 PM: \\?\DISPLAY#CMN1556#5&2baa1933&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
4/19/2024 8:50:56 PM: \\?\DISPLAY#CMN1556#5&2baa1933&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/19/2024 8:50:56 PM: N156HMA-GA1 HDR: False 8 4 True
4/19/2024 8:50:56 PM: Mode = 0 : OK
4/19/2024 8:50:56 PM: TUF_KB = 16712125 : OK
4/19/2024 8:50:56 PM: AuraMode: AuraStatic
4/19/2024 8:50:56 PM: TUF RGB = B4-00-FF-FF-FF-EB : OK
4/19/2024 8:50:56 PM: Detected a newTUF GAMING M3 (Gen II) . Connecting...
4/19/2024 8:50:56 PM: N156HMA-GA1 HDR: False 8 4 True
4/19/2024 8:50:57 PM: Monitor Power On
4/19/2024 8:50:57 PM: Lid Open
4/19/2024 8:50:57 PM: TUF Brightness = 129 : OK
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II) synchronising. Try 1
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Write took 7ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Active Profile 1, Active DPI Profile: 0
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read DPI Setting 1: DPI: 800, Color (255, 0, 0)
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read DPI Setting 2: DPI: 1600, Color (255, 0, 0)
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read DPI Setting 3: DPI: 3200, Color (255, 0, 0)
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read DPI Setting 4: DPI: 6400, Color (255, 0, 0)
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Pollingrate: 1000 Hz (PR1000Hz)
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Angle Snapping enabled: False, Angle Adjustment: 0°
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read Debouce Setting: MS12
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II): Read RGB Setting for Zone Logo: LightingMode: Static, Color (255, 255, 255), Brightness: 100%, LightingSpeed: Medium, RandomColor:False, AnimationDirection:Clockwise
4/19/2024 8:50:57 PM: TUF GAMING M3 (Gen II) added to the list: 1 device are conneted.
4/19/2024 8:50:57 PM: TUF Brightness = 129 : OK
4/19/2024 8:50:58 PM: Latest version 0.167.0.0
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II) (GUI): Initialized capabilities. Synchronizing mouse data
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Write took 3ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Active Profile 1, Active DPI Profile: 0
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read DPI Setting 1: DPI: 800, Color (255, 0, 0)
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read DPI Setting 2: DPI: 1600, Color (255, 0, 0)
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read DPI Setting 3: DPI: 3200, Color (255, 0, 0)
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read DPI Setting 4: DPI: 6400, Color (255, 0, 0)
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Pollingrate: 1000 Hz (PR1000Hz)
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Angle Snapping enabled: False, Angle Adjustment: 0°
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read Debouce Setting: MS12
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Write took 2ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read took 1ms
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II): Read RGB Setting for Zone Logo: LightingMode: Static, Color (255, 255, 255), Brightness: 100%, LightingSpeed: Medium, RandomColor:False, AnimationDirection:Clockwise
4/19/2024 8:51:05 PM: TUF GAMING M3 (Gen II) (GUI): Mouse data synchronized
4/19/2024 8:51:06 PM: Input device not found
```
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GHelper.AsusMouseSettings.VisualizeCurrentDPIProfile() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 869
   at GHelper.AsusMouseSettings.VisualizeMouseSettings() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 693
   at GHelper.AsusMouseSettings.RefreshMouseData() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 473
   at GHelper.AsusMouseSettings..ctor(AsusMouse mouse) in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 114
   at GHelper.SettingsForm.ButtonPeripheral_Click(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Settings.cs:line 1810
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.CoreLib.dll
----------------------------------------
GHelper
    Assembly Version: 0.167.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.Uri.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Encodings.Web.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Claims.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Drawing.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.dll
----------------------------------------
WinForms.DataVisualization
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WinForms.DataVisualization.Utilities
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/netstandard.dll
----------------------------------------
HidSharpCore
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.Xml.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.Loader.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.PerformanceCounter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.NonGeneric.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.Overlapped.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Cryptography.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Quic.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************


```

**Comment by seerge** [comment]
@lenverwazo ok, try this one
[GHelper.zip](https://github.com/seerge/g-helper/files/15044835/GHelper.zip)

**Comment by lenverwazo** [comment]
Hi again! Still an issue unfortunately. The error's more specific in the log: `Wrong mouse DPI: 0 Index was outside the bounds of the array.`

**Comment by seerge** [comment]
@lenverwazo ok, and this one ?

[GHelper.zip](https://github.com/seerge/g-helper/files/15047451/GHelper.zip)

**Comment by lenverwazo** [comment]
Works great, I'm closing the issue! Looking forward for the next official patch.
