### ISSUE TITLE
Unhandled exception error when I close and open the lid of my ASUS GX551QS (ROG Zephyrus DUO 15 SE)

### ISSUE THREAD

**Issue by MegaDestroyer1** [seerge/g-helper#2556]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whenever I switch to iGPU mode, and close the lid of the laptop to put it on standby, whenever I open the lid afterwards a popup appears from the Microsoft .NET framework, telling me that an unhandled exception has occurred. Even after enabling the GPU afterwards, nothing seems to help.
![image](https://github.com/seerge/g-helper/assets/140008910/fc5cc267-15ab-4b92-871c-f9c44577ed09)

### How to reproduce the bug?

1. Disable dGPU by going into eco mode (iGPU only)
2. Wait some time, I find it takes about 5 minutes to set in.
3. click the cross on the top right corner of G-helper
4. Close the laptop lid
5. Open the laptop lid
6. you should have the exception, idk if it happens every single time

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15223296/log.txt)

### Device and Model

Asus ROG Zephyrus Duo 15 SE GX551QS

### Additional information.

The exception window reads:

"Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

A device attached to the system is not functioning."

Under the drop-down menu labelled "Details", it reads: 

"
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (31): A device attached to the system is not functioning.
   at GHelper.Display.ScreenCCD.GetHDRStatus(Boolean log) in D:\a\g-helper\g-helper\app\Display\ScreenCCD.cs:line 42
   at GHelper.Display.ScreenControl.InitScreen() in D:\a\g-helper\g-helper\app\Display\ScreenControl.cs:line 162
   at GHelper.Display.ScreenControl.SetScreen(Int32 frequency, Int32 overdrive, Int32 miniled) in D:\a\g-helper\g-helper\app\Display\ScreenControl.cs:line 74
   at GHelper.Display.ScreenControl.AutoScreen(Boolean force) in D:\a\g-helper\g-helper\app\Display\ScreenControl.cs:line 16
   at GHelper.Program.SetAutoModes(Boolean powerChanged, Boolean init) in D:\a\g-helper\g-helper\app\Program.cs:line 231
   at GHelper.SettingsForm.WndProc(Message& m) in D:\a\g-helper\g-helper\app\Settings.cs:line 675
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.CoreLib.dll
----------------------------------------
GHelper
    Assembly Version: 0.170.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.Uri.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Encodings.Web.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Claims.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Drawing.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1824.16917
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ComponentModel.dll
----------------------------------------
WinForms.DataVisualization
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WinForms.DataVisualization.Utilities
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/netstandard.dll
----------------------------------------
HidSharpCore
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Private.Xml.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.Loader.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.PerformanceCounter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.18/System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Threading.Overlapped.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.NonGeneric.dll
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Data.Common.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Security.Cryptography.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Quic.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1824.16914
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.18/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
"

I don't know if this helps. There are also two buttons, "Continue", and "quit". If you press Quit, well, the program stops, and if you press "Continue", the program continues running and seems to work fine until you close the lid and open it again, as another exception pops up.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

v0.170

### OS

Windows 10 home version 22H2

**Comment by seerge** [comment]
@MegaDestroyer1 hello, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15223935/GHelper.zip)

**Comment by MegaDestroyer1** [comment]
Thanks! The exception doesn't seem to happen anymore.
