### ISSUE TITLE
High voltage usage after update

### ISSUE THREAD

**Issue by MarcosOlegario1** [seerge/g-helper#339]
*Model: GA402RJ*

After update to 0.58, using egpu eco mode and cpu in silent mode, my same usage as last version is almost double...

Configs reproduction:
 - Only G Helper, Armoury debloated (0.58 version)
 - Processor in silent processor tdp in 35w and total tdp is 100w
 - Screen in 60hz with 20% brightness also keyboard ilumination off
 - Only watching twitch with sound in 10.
 - Fans off with curve
 - Wifi in 2.4ghz
  - Tryed turn on save battery mode, but not effects.
  
  Behavior with the same configs (fact that i was using cpu tdp in 40w) the power consumption was 8-10w, now is ~15.
  
  
<img width="827" alt="image" src="https://user-images.githubusercontent.com/9780393/236952669-c50b7185-e84a-4917-bebb-03e5d3c0d9ae.png">

**log below**
  
09/05/2023 00:56:46: System.DllNotFoundException: Unable to load DLL 'nvapi64' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId) in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 62
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 40
   at NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\GPUApi.cs:line 62
   at NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\GPU\PhysicalGPU.cs:line 302
   at GHelper.Gpu.NvidiaGpuControl.GetInternalDiscreteGpu() in C:\Users\serge\g-helper\app\Gpu\NvidiaGpuControl.cs:line 115
09/05/2023 00:56:46: ------------
09/05/2023 00:56:46: App launched: ROG Zephyrus G14 GA402RJ_GA402RJ :0.58.0.0N
09/05/2023 00:56:47: AutoSetting for Offline
09/05/2023 00:56:47: BatteryLimit = 100 : OK
09/05/2023 00:56:47: BatteryLimit = 100 : OK
09/05/2023 00:56:47: PerformanceMode = 2 : OK
09/05/2023 00:56:47: FanCPU = 3C-41-42-46-49-50-57-63-00-0C-0C-14-1D-28-2C-37 : OK
09/05/2023 00:56:47: FanGPU = 3B-41-42-46-47-4B-4C-62-00-11-11-1D-1D-26-26-2D : OK
09/05/2023 00:56:47: Boost 0
09/05/2023 00:56:47: Eco flag : 1
09/05/2023 00:56:47: Mux flag : 1
09/05/2023 00:56:47: Screen = 60Hz : OK
09/05/2023 00:56:47: ScreenOverdrive = 0 : OK
09/05/2023 00:56:48: PowerLimit A0 = 100 : OK
09/05/2023 00:56:48: PowerLimit A3 = 100 : OK
09/05/2023 00:56:48: PowerLimit B0 = 40 : OK
09/05/2023 00:56:48: Matrix Off
09/05/2023 00:56:48: System.DllNotFoundException: Unable to load DLL 'nvapi64' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId) in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 62
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 40
   at NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\GPUApi.cs:line 62
   at NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\GPU\PhysicalGPU.cs:line 302
   at GHelper.Gpu.NvidiaGpuControl.GetInternalDiscreteGpu() in C:\Users\serge\g-helper\app\Gpu\NvidiaGpuControl.cs:line 115
09/05/2023 00:56:48: Monitor Power On
09/05/2023 01:00:12: System.DllNotFoundException: Unable to load DLL 'nvapi64' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId) in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 62
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 40
   at NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\GPUApi.cs:line 62
   at NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\GPU\PhysicalGPU.cs:line 302
   at GHelper.Gpu.NvidiaGpuControl.GetInternalDiscreteGpu() in C:\Users\serge\g-helper\app\Gpu\NvidiaGpuControl.cs:line 115
09/05/2023 01:00:12: ------------
09/05/2023 01:00:13: App launched: ROG Zephyrus G14 GA402RJ_GA402RJ :0.58.0.0N
09/05/2023 01:00:14: AutoSetting for Offline
09/05/2023 01:00:14: BatteryLimit = 100 : OK
09/05/2023 01:00:14: BatteryLimit = 100 : OK
09/05/2023 01:00:14: PerformanceMode = 2 : OK
09/05/2023 01:00:14: FanCPU = 3C-41-42-46-49-50-57-63-00-0C-0C-14-1D-28-2C-37 : OK
09/05/2023 01:00:14: FanGPU = 3B-41-42-46-47-4B-4C-62-00-11-11-1D-1D-26-26-2D : OK
09/05/2023 01:00:14: Boost 0
09/05/2023 01:00:14: Eco flag : 1
09/05/2023 01:00:14: Mux flag : 1
09/05/2023 01:00:15: Screen = 60Hz : OK
09/05/2023 01:00:15: ScreenOverdrive = 0 : OK
09/05/2023 01:00:15: PowerLimit A0 = 100 : OK
09/05/2023 01:00:15: PowerLimit A3 = 100 : OK
09/05/2023 01:00:15: PowerLimit B0 = 40 : OK
09/05/2023 01:00:16: USB-KB = 5D-BA-C5-C4-00
09/05/2023 01:00:16: Matrix Off
09/05/2023 01:00:16: System.DllNotFoundException: Unable to load DLL 'nvapi64' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId) in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 62
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\Helpers\DelegateFactory.cs:line 40
   at NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\Native\GPUApi.cs:line 62
   at NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs() in C:\Users\serge\g-helper\app\NvAPIWrapper\GPU\PhysicalGPU.cs:line 302
   at GHelper.Gpu.NvidiaGpuControl.GetInternalDiscreteGpu() in C:\Users\serge\g-helper\app\Gpu\NvidiaGpuControl.cs:line 115
09/05/2023 01:00:16: Monitor Power On
09/05/2023 01:07:34: WMI event 197
09/05/2023 01:07:34: WMI event 196
09/05/2023 01:07:35: WMI event 197
09/05/2023 01:08:22: PowerLimit A0 = 100 : OK
09/05/2023 01:08:22: PowerLimit A3 = 100 : OK
09/05/2023 01:08:22: PowerLimit B0 = 35 : OK
09/05/2023 01:08:30: Screen = 60Hz : OK
09/05/2023 01:08:30: ScreenOverdrive = 0 : OK
09/05/2023 01:08:33: Screen = 60Hz : OK
09/05/2023 01:08:33: ScreenOverdrive = 0 : OK
09/05/2023 01:08:34: Screen = 60Hz : OK
09/05/2023 01:08:34: ScreenOverdrive = 0 : OK

**Comment by seerge** [comment]
@MarcosOlegario1 hello, i would rather attribute your higher usage to other factors, as it's literally nothing changed in the app that could affect that :) Main addition in 0.58 is nvidia overclock,  that is completely off on G14 2022 due to absense of nvidia there.

Furthermore, app doesn't "control" your power usage in a first place (maximum it can do is set power limits, that are still much higher than your usage)

Just to confirm, you can download any previous version from releases https://github.com/seerge/g-helper/releases (for example 0.55 that you probably had) and see if something changes.

**Comment by MarcosOlegario1** [comment]
> @MarcosOlegario1 hello, i would rather attribute your higher usage to other factors, as it's literally nothing changed in the app that could affect that :) Main addition in 0.58 is nvidia overclock, that is completely off on G14 2022 due to absense of nvidia there.
> 
> Furthermore, app doesn't "control" your power usage in a first place (maximum it can do is set power limits, that are still much higher than your usage)
> 
> Just to confirm, you can download any previous version from releases https://github.com/seerge/g-helper/releases (for example 0.55 that you probably had) and see if something changes.
> 
> P.S. Check task manager for whats running and taking power on your laptop.

Thanks for the answer.
