### ISSUE TITLE
Ghelper wont run

### ISSUE THREAD

**Issue by Priboiii** [seerge/g-helper#3480]
ghelper used to run perfectly fine since i downloaded it but from yesterday it wont open at all.

This is what it says in event viewer:

Application: GHelper.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070032): The request is not supported. (0x80070032)
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskService.Connect(Object serverName, Object user, Object domain, Object password)
   at Microsoft.Win32.TaskScheduler.TaskService.Connect()
   at Microsoft.Win32.TaskScheduler.TaskService..ctor()
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Microsoft.Win32.TaskScheduler.TaskService..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Win32.TaskScheduler.TaskService.GetLibraryVersionFromLocalOS()
   at Microsoft.Win32.TaskScheduler.TaskService.ResetHighestSupportedVersion()
   at Microsoft.Win32.TaskScheduler.TaskService..ctor()
   at Startup.IsScheduled() in D:\a\g-helper\g-helper\app\Helpers\Startup.cs:line 14
   at GHelper.SettingsForm..ctor() in D:\a\g-helper\g-helper\app\Settings.cs:line 189
   at GHelper.Program..cctor() in D:\a\g-helper\g-helper\app\Program.cs:line 30
   --- End of inner exception stack trace ---
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 83

i tried uninstalling and reinstalling latest .net version but still nothing. please help.

**Comment by seerge** [comment]
@Priboiii hello,

It looks some internal exception in windows Task Scheduler (that G-Helper uses to set itself to run on startup and checks the status every time you run it)

Try to manually open Task Scheduler and remove GHelper task from there, to see if it helps ?

If not try this build, I have suppressed exception, so at least app will keep running (but it won't be able to check if it's scheduled tho)

[GHelper.zip](https://github.com/user-attachments/files/18128448/GHelper.zip)

**Comment by seerge** [comment]
@Priboiii any updates here ?
