### ISSUE TITLE
[Bug] Crash at startup, v0.64, G15 2021

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#414]
**Describe the bug**
The new version can't start with the next error:
```
Application: GHelper.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at GHelper.AnimeMatrix.AniMatrix..ctor() in C:\Users\Serge\g-helper\app\AnimeMatrix\AniMatrix.cs:line 34
   at GHelper.SettingsForm.InitMatrix() in C:\Users\Serge\g-helper\app\Settings.cs:line 660
   at GHelper.Program.Main(String[] args) in C:\Users\Serge\g-helper\app\Program.cs:line 79
```
**Clear scenario to Reproduce**
Just Run the app.

**Expected behavior**
It works. =)

**App Logs**
That's literally all log:
```
19.05.2023 14:20:36: ------------
19.05.2023 14:20:36: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.64.0.0
```

**Desktop (please complete the following information):**
 - OS: Windows 11 22h2
 - Laptop model: GA503QR

**Asus software**
- MyASUS
- AsusAppService
- ASUSSoftwareManager
- ASUSOptimization

**Comment by seerge** [comment]
@ke1ne can you check if this one works fine for you ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11516434/GHelper.zip)

**Comment by ke1ne** [comment]
> @ke1ne can you check if this one works fine for you ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11516434/GHelper.zip)

This one works, but also proposes me to manage AnimeMatrix which I haven't.

**Comment by seerge** [comment]
@ke1ne and this one ? :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/11516496/GHelper.zip)

**Comment by ke1ne** [comment]
> @ke1ne and this one ? :) [GHelper.zip](https://github.com/seerge/g-helper/files/11516496/GHelper.zip)

Seems to be OK. Thanks!

Also, there is a small visual issue in fan curves. A wrong overflow at the bottom:
![image](https://github.com/seerge/g-helper/assets/8934421/bf925462-ba60-4c29-b737-ef4dfafa6367)

**Comment by seerge** [comment]
I have re-uploaded this fix over existing https://github.com/seerge/g-helper/releases/tag/v0.64
