### ISSUE TITLE
Bios rejected fan curve After Version 0.63 on TUF laptop

### ISSUE THREAD

**Issue by soundwaves7** [seerge/g-helper#458]
**Describe the bug**
Every Version after "v0.63" gives the message "Bios rejected fan curve."
Version v0.63 is working fine
Tested All Versions After v0.63 up-to v0.69 all has the same problem

**Clear scenario to Reproduce**
1. Apply custom fan curve

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/11563843/log.txt) Ver: 0.63
[log.txt](https://github.com/seerge/g-helper/files/11563876/log.txt) Ver: 0.67

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/25686789/ce8653e8-9f0a-4d90-ac25-03943adc29bf)
![image](https://github.com/seerge/g-helper/assets/25686789/27f27707-48af-4b33-8e7b-999e776b175c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Asus Tuf F17 2021 FX706HE

**Asus software**
- Armoury crate Not Installed but some services Installed
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
@soundwaves7 hello, from log it's pretty much clear that bios was rejecting your fan curve in 0.63 as well (i assume they are not supported on your laptop at all)

```
25/05/2023 1:33:06 PM: App launched: ASUS TUF Gaming F17 FX706HE_FX706HE :0.63.0.0A
25/05/2023 1:33:06 PM: AutoSetting for Online
25/05/2023 1:33:06 PM: BatteryLimit = 80 : OK
25/05/2023 1:33:06 PM: PerformanceMode = 0 : OK
25/05/2023 1:33:06 PM: GET GPU CLOCKS: 55, 150
25/05/2023 1:33:06 PM: FanCPU = 14-3A-3D-40-48-4D-51-58-00-08-11-16-22-29-30-63 : 0
25/05/2023 1:33:06 PM: FanGPU = 14-3A-3D-40-48-4D-51-58-00-0C-16-1D-26-2D-34-63 : 0
25/05/2023 1:33:06 PM: ASUS BIOS rejected fan curve, resetting mode to 0
```

I just fixed UI bug that could keep label (with warning) invisible :)

**Comment by soundwaves7** [comment]
oh so that's normal for my laptop model or something wrong with my bios?

**Comment by seerge** [comment]
@soundwaves7 did you had (working) fan curves in armoury crate in a first place ? If not - that's absolutely normal.

**Comment by soundwaves7** [comment]
oh no i didn't, thank you :)

**Comment by soundwaves7** [comment]
on an unrelated matter on the latest version i get this error when trying to adjust the volume

![image](https://github.com/seerge/g-helper/assets/25686789/01b6e6b9-4454-4537-99d9-65a13c946db9)

***Details***
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at GHelper.InputDispatcher.LaunchProcess(String command) in C:\Users\Serge\g-helper\app\InputDispatcher.cs:line 330
   at GHelper.InputDispatcher.CustomKey(String configKey) in C:\Users\Serge\g-helper\app\InputDispatcher.cs:line 175
   at GHelper.InputDispatcher.KeyProcess(String name) in C:\Users\Serge\g-helper\app\InputDispatcher.cs:line 225
   at GHelper.SettingsForm.WndProc(Message& m) in C:\Users\Serge\g-helper\app\Settings.cs:line 202
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.CoreLib.dll
----------------------------------------
GHelper
    Assembly Version: 0.69.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.Uri.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.Encodings.Web.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ObjectModel.dll
----------------------------------------
WinForms.DataVisualization
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WinForms.DataVisualization.Utilities
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/netstandard.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Security.Claims.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Loader.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Linq.dll
----------------------------------------
HidSharpCore
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.Xml.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Intrinsics.dll
----------------------------------------
System.Diagnostics.PerformanceCounter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Security.Cryptography.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.Quic.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Net.NameResolution.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.NonGeneric.dll
----------------------------------------
HidLibrary
    Assembly Version: 3.2.49.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************

**Comment by seerge** [comment]
@soundwaves7 i assume you had a custom binding selected for M1 or M2? Try to set it bacl to volume up / down.

And this build should supress an error at least

[GHelper.zip](https://github.com/seerge/g-helper/files/11564218/GHelper.zip)

**Comment by soundwaves7** [comment]
that fixed it , thanks
